//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProSoft.EasySave.Presentation.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProSoft.EasySave.Presentation.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a business software executable..
        /// </summary>
        public static string APP_BUIS1 {
            get {
                return ResourceManager.GetString("APP_BUIS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business software detection.
        /// </summary>
        public static string APPS_BUIS_TITLE {
            get {
                return ResourceManager.GetString("APPS_BUIS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When its use is detected, all ongoing saves will be stopped..
        /// </summary>
        public static string APPS_BUIS2 {
            get {
                return ResourceManager.GetString("APPS_BUIS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File priority selection.
        /// </summary>
        public static string APPS_FILE_TITLE {
            get {
                return ResourceManager.GetString("APPS_FILE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose below the extensions of files that should be prioritized..
        /// </summary>
        public static string APPS_FILE1 {
            get {
                return ResourceManager.GetString("APPS_FILE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The priority is set from left to right..
        /// </summary>
        public static string APPS_FILE2 {
            get {
                return ResourceManager.GetString("APPS_FILE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible extensions : pdf, doc, docx, txt, xls, xlsx, json, iso, jpeg, png.
        /// </summary>
        public static string APPS_FILE3 {
            get {
                return ResourceManager.GetString("APPS_FILE3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example : pdf;docx;txt.
        /// </summary>
        public static string APPS_FILE4 {
            get {
                return ResourceManager.GetString("APPS_FILE4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log folder.
        /// </summary>
        public static string APPS_LOG_TITLE {
            get {
                return ResourceManager.GetString("APPS_LOG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This button opens an explorer to the folder containing the logs.
        /// </summary>
        public static string APPS_LOG1 {
            get {
                return ResourceManager.GetString("APPS_LOG1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application settings.
        /// </summary>
        public static string APPS_TITLE {
            get {
                return ResourceManager.GetString("APPS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max allowed file weight.
        /// </summary>
        public static string APPS_WEIGHT_TITLE {
            get {
                return ResourceManager.GetString("APPS_WEIGHT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If two files exceed this weight (in kiloBytes),.
        /// </summary>
        public static string APPS_WEIGHT1 {
            get {
                return ResourceManager.GetString("APPS_WEIGHT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to they will be saved one after the other and not simultaneously..
        /// </summary>
        public static string APPS_WEIGHT2 {
            get {
                return ResourceManager.GetString("APPS_WEIGHT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HOME {
            get {
                return ResourceManager.GetString("HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string NAV_CONFIG {
            get {
                return ResourceManager.GetString("NAV_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string NAV_HOME {
            get {
                return ResourceManager.GetString("NAV_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Selection.
        /// </summary>
        public static string NAV_SAVE_SELECTION {
            get {
                return ResourceManager.GetString("NAV_SAVE_SELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause all backup.
        /// </summary>
        public static string PAUSE_ALL_SAVE {
            get {
                return ResourceManager.GetString("PAUSE_ALL_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit.  Aenean quis enim nec sem dapibus ullamcorper eu sed ligula. Nam ultricies lorem eu libero dapibus, aliquam mattis ante faucibus. Maecenas ipsum urna, condimentum id erat at, consectetur varius ipsum. Duis cursus lectus nisi,  ut ultrices ex scelerisque eu. Quisque eros tellus, viverra nec luctus at, fermentum vitae metus. Vestibulum congue lobortis vulputate. n hac habitasse platea dictumst. Integer molestie libero ornare, placerat arcu sit amet, ult [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SAMPLE_BIG_TEXT {
            get {
                return ResourceManager.GetString("SAMPLE_BIG_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 saves in progress.
        /// </summary>
        public static string SAMPLE_CONFIG_TEXT {
            get {
                return ResourceManager.GetString("SAMPLE_CONFIG_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1234.
        /// </summary>
        public static string SAMPLE_NUMBER1 {
            get {
                return ResourceManager.GetString("SAMPLE_NUMBER1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample title.
        /// </summary>
        public static string SAMPLE_TITLE {
            get {
                return ResourceManager.GetString("SAMPLE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to ConfigScreen.
        /// </summary>
        public static string SAMPLE_TITLE_CONFIG {
            get {
                return ResourceManager.GetString("SAMPLE_TITLE_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatPlaceholder.
        /// </summary>
        public static string SAMPLE_TITLE_STAT {
            get {
                return ResourceManager.GetString("SAMPLE_TITLE_STAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destiantion path.
        /// </summary>
        public static string SAVEC_DEST {
            get {
                return ResourceManager.GetString("SAVEC_DEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SAVEC_NAME {
            get {
                return ResourceManager.GetString("SAVEC_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save type.
        /// </summary>
        public static string SAVEC_SAVE_TYPE {
            get {
                return ResourceManager.GetString("SAVEC_SAVE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source paths.
        /// </summary>
        public static string SAVEC_SOURCE {
            get {
                return ResourceManager.GetString("SAVEC_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves configuration.
        /// </summary>
        public static string SAVEC_TITLE {
            get {
                return ResourceManager.GetString("SAVEC_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start all backup.
        /// </summary>
        public static string START_ALL_SAVE {
            get {
                return ResourceManager.GetString("START_ALL_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TAB_NAME {
            get {
                return ResourceManager.GetString("TAB_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string TAB_PROGRESS {
            get {
                return ResourceManager.GetString("TAB_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source file.
        /// </summary>
        public static string TAB_SOURCE {
            get {
                return ResourceManager.GetString("TAB_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string TAB_STATUS {
            get {
                return ResourceManager.GetString("TAB_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target file.
        /// </summary>
        public static string TAB_TARGET {
            get {
                return ResourceManager.GetString("TAB_TARGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save/Backup in progress.
        /// </summary>
        public static string TAB_TITLE {
            get {
                return ResourceManager.GetString("TAB_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfert Type.
        /// </summary>
        public static string TAB_TRANSFERT {
            get {
                return ResourceManager.GetString("TAB_TRANSFERT", resourceCulture);
            }
        }
    }
}
